In [3]:
import requests
import pandas as pd

In [ ]:
resp = requests.get(f'http://api.aviationstack.com/v1/flights?access_key=87dd9fd89252e3dd72707f1435c58969&airline_iata=PK')

## IATA Codes for Airlines in Pakistan
- Airsial       PF
- PIA           PK
- Serene Air    ER
- Flyjinah      9P
- Airblue       PA

In [ ]:
data = resp.json()
data

In [1]:
# Lambda Code
import json
import urllib3

def lambda_handler(event, context):
    http = urllib3.PoolManager()

    url = "http://api.aviationstack.com/v1/flights?access_key=87dd9fd89252e3dd72707f1435c58969&airline_iata=PK"

    resp = http.request("GET", url)

    # decode response body (bytes → str → JSON)
    data = json.loads(resp.data.decode("utf-8"))

    return data

In [ ]:
df = pd.json_normalize(data["data"], sep="_")
print(df)

In [11]:
df.columns

Index(['flight_date', 'flight_status', 'aircraft', 'live', 'departure_airport',
       'departure_timezone', 'departure_iata', 'departure_icao',
       'departure_terminal', 'departure_gate', 'departure_delay',
       'departure_scheduled', 'departure_estimated', 'departure_actual',
       'departure_estimated_runway', 'departure_actual_runway',
       'arrival_airport', 'arrival_timezone', 'arrival_iata', 'arrival_icao',
       'arrival_terminal', 'arrival_gate', 'arrival_baggage',
       'arrival_scheduled', 'arrival_delay', 'arrival_estimated',
       'arrival_actual', 'arrival_estimated_runway', 'arrival_actual_runway',
       'airline_name', 'airline_iata', 'airline_icao', 'flight_number',
       'flight_iata', 'flight_icao', 'flight_codeshared',
       'flight_codeshared_airline_name', 'flight_codeshared_airline_iata',
       'flight_codeshared_airline_icao', 'flight_codeshared_flight_number',
       'flight_codeshared_flight_iata', 'flight_codeshared_flight_icao'],
      dtype='object')

In [14]:
df = df.drop(["aircraft", "live", "departure_estimated_runway", "departure_actual_runway", "arrival_estimated_runway", "arrival_actual_runway"], axis=1)

In [15]:
df.head()

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_terminal,departure_gate,departure_delay,departure_scheduled,...,flight_number,flight_iata,flight_icao,flight_codeshared,flight_codeshared_airline_name,flight_codeshared_airline_iata,flight_codeshared_airline_icao,flight_codeshared_flight_number,flight_codeshared_flight_iata,flight_codeshared_flight_icao
0,2025-08-26,active,Quaid-e-azam International,Asia/Karachi,KHI,OPKC,M,None,20.0,2025-08-26T08:25:00+00:00,...,783,PK783,PIA783,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-08-26,scheduled,Quaid-e-azam International,Asia/Karachi,KHI,OPKC,M,None,NaN,2025-08-26T10:15:00+00:00,...,455,PK455,PIA455,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-08-26,scheduled,Islamabad International,Asia/Karachi,ISB,OPIS,None,None,4.0,2025-08-26T10:00:00+00:00,...,301,PK301,PIA301,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-08-26,scheduled,Quaid-e-azam International,Asia/Karachi,KHI,OPKC,M,None,NaN,2025-08-26T14:00:00+00:00,...,304,PK304,PIA304,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-08-26,landed,Multan International,Asia/Karachi,MUX,OPMT,None,None,NaN,2025-08-26T01:00:00+00:00,...,221,PK221,PIA221,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.to_csv("flights.csv")

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 36 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   flight_date                      100 non-null    datetime64[ns]
 1   flight_status                    99 non-null     object
 2   departure_airport                100 non-null    object
 3   departure_timezone               100 non-null    object
 4   departure_iata                   100 non-null    object
 5   departure_icao                   100 non-null    object
 6   departure_terminal               44 non-null     object
 7   departure_gate                   40 non-null     object
 8   departure_delay                  59 non-null     float64
 9   departure_scheduled              100 non-null    datetime64[ns, UTC]
 10  departure_estimated              100 non-null    datetime64[ns, UTC]
 11  departure_actual                 54 non-null     datetime64[ns, UTC]
 12  arrival_airport                  100 non-null    object
 13  arrival_timezone                 100 non-null    object
 14  arrival_iata                     100 non-null    object
 15  arrival_icao                     100 non-null    object
 16  arrival_terminal                 54 non-null     object
 17  arrival_gate                     5 non-null      object
 18  arrival_baggage                  35 non-null     object
 19  arrival_scheduled                100 non-null    datetime64[ns, UTC]
 20  arrival_delay                    15 non-null     float64
 21  arrival_estimated                54 non-null     datetime64[ns, UTC]
 22  arrival_actual                   37 non-null     datetime64[ns, UTC]
 23  airline_name                     100 non-null    object
 24  airline_iata                     100 non-null    object
 25  airline_icao                     100 non-null    object
 26  flight_number                    100 non-null    object
 27  flight_iata                      100 non-null    object
 28  flight_icao                      100 non-null    object
 29  flight_codeshared                0 non-null      float64
 30  flight_codeshared_airline_name   69 non-null     object
 31  flight_codeshared_airline_iata   69 non-null     object
 32  flight_codeshared_airline_icao   69 non-null     object
 33  flight_codeshared_flight_number  69 non-null     object
 34  flight_codeshared_flight_iata    69 non-null     object
 35  flight_codeshared_flight_icao    69 non-null     object
dtypes: datetime64[ns, UTC](6), datetime64[ns](1), float64(3), object(26)
memory usage: 28.3+ KB

In [32]:
# df["flight_date"] = pd.to_datetime(df["flight_date"])
# df["departure_scheduled"] = pd.to_datetime(df["departure_scheduled"])
# df["departure_estimated"] = pd.to_datetime(df["departure_estimated"])
# df["departure_actual"] = pd.to_datetime(df["departure_actual"])
# df["arrival_scheduled"] = pd.to_datetime(df["arrival_scheduled"])
# df["arrival_estimated"] = pd.to_datetime(df["arrival_estimated"])
# df["arrival_actual"] = pd.to_datetime(df["arrival_actual"])
cols_to_convert = [
    "flight_date",
    "departure_scheduled",
    "departure_estimated",
    "departure_actual",
    "arrival_scheduled",
    "arrival_estimated",
    "arrival_actual"
]
df[cols_to_convert] = df[cols_to_convert].apply(pd.to_datetime, errors="coerce")

In [24]:
# Lambda Transformation Code
import json
import boto3
import pandas as pd
from datetime import datetime
from io import StringIO

s3 = boto3.client("s3")
BUCKET = "flight-data-project-kk"

def lambda_handler(event, context):
    # Always work on today's date
    now = datetime.utcnow()
    raw_key = f"raw/{now.year}/{now.month:02d}/{now.day:02d}/flights.json"
    processed_key = f"processed/{now.year}/{now.month:02d}/{now.day:02d}/flights.csv"

    try:
        # Get raw JSON from S3
        response = s3.get_object(Bucket=BUCKET, Key=raw_key)
        raw_data = response["Body"].read().decode("utf-8")
        data = json.loads(raw_data)

        # Convert JSON -> DataFrame
        df = pd.json_normalize(data["data"], sep="_")

        # Drop unwanted columns
        df = df.drop(
            ["aircraft", "live", "departure_estimated_runway",
             "departure_actual_runway", "arrival_estimated_runway",
             "arrival_actual_runway"],
            axis=1,
            errors="ignore"  # in case any column missing
        )

        # Convert datetime columns
        cols_to_convert = [
            "flight_date",
            "departure_scheduled",
            "departure_estimated",
            "departure_actual",
            "arrival_scheduled",
            "arrival_estimated",
            "arrival_actual"
        ]
        df[cols_to_convert] = df[cols_to_convert].apply(pd.to_datetime, errors="coerce")

        # Save DataFrame to CSV in-memory
        csv_buffer = StringIO()
        df.to_csv(csv_buffer, index=False)

        # Upload processed CSV to S3
        s3.put_object(
            Bucket=BUCKET,
            Key=processed_key,
            Body=csv_buffer.getvalue(),
            ContentType="text/csv"
        )

        return {
            "statusCode": 200,
            "body": f"Processed data saved to s3://{BUCKET}/{processed_key}"
        }

    except s3.exceptions.NoSuchKey:
        return {
            "statusCode": 404,
            "body": f"No raw data found for today at s3://{BUCKET}/{raw_key}"
        }